=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ExpediaRapid::GeographyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GeographyApi' do
  before do
    # run before each test
    @api_instance = ExpediaRapid::GeographyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GeographyApi' do
    it 'should create an instance of GeographyApi' do
      expect(@api_instance).to be_instance_of(ExpediaRapid::GeographyApi)
    end
  end

  # unit tests for get_region
  # Region
  # Returns the geographic definition and property mappings for the requested Region ID. The response is a single JSON formatted region object. 
  # @param accept Specifies the response format that the client would like to receive back. This must be &#x60;application/json&#x60;. 
  # @param accept_encoding Specifies the response encoding that the client would like to receive back. This must be &#x60;gzip&#x60;. 
  # @param user_agent The &#x60;User-Agent&#x60; header string from the customer&#39;s request, as captured by your integration. If you are building an application then the &#x60;User-Agent&#x60; value should be &#x60;{app name}/{app version}&#x60;. 
  # @param region_id ID of the region to retrieve. 
  # @param language Desired language for the response as a subset of BCP47 format that only uses hyphenated pairs of two-digit language and country codes. Use only ISO 639-1 alpha-2 language codes and ISO 3166-1 alpha-2 country codes. See [https://www.w3.org/International/articles/language-tags/](https://www.w3.org/International/articles/language-tags/)  Language Options: [https://developers.expediagroup.com/docs/rapid/resources/reference/language-options](https://developers.expediagroup.com/docs/rapid/resources/reference/language-options) 
  # @param include Options for which content to return in the response. This parameter can be supplied multiple times with different values. The value must be lower case.   * details - Include the metadata, coordinates and full hierarchy of the region.   * property_ids - Include the list of property IDs within the bounding polygon of the region.   * property_ids_expanded - Include the list of property IDs within the bounding polygon of the region and property IDs from the surrounding area if minimal properties are within the region. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_session_id Insert your own unique value for each user session, beginning with the first API call. Continue to pass the same value for each subsequent API call during the user&#39;s session, using a new value for every new customer session.&lt;br&gt; Including this value greatly eases EPS&#39;s internal debugging process for issues with partner requests, as it explicitly links together request paths for individual user&#39;s session. 
  # @option opts [String] :supply_source Options for which supply source you would like returned in the geography response. This parameter may only be supplied once and will return all properties that match the requested supply source. An error is thrown if the parameter is provided multiple times.   * &#x60;expedia&#x60; - Standard Expedia supply.   * &#x60;vrbo&#x60; - VRBO supply - This option is restricted to partners who have VRBO supply enabled for their profile. See [Vacation Rentals](https://developers.expediagroup.com/docs/rapid/lodging/vacation-rentals) for more information. 
  # @option opts [String] :billing_terms This parameter is to specify the terms of how a resulting booking should be billed. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :partner_point_of_sale This parameter is to specify what point of sale is being used to shop and book. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :payment_terms This parameter is to specify what terms should be used when being paid for a resulting booking. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :platform_name This parameter is to specify what platform is being used to shop and book. If this field is needed, the value for this will be provided to you separately. 
  # @return [Region]
  describe 'get_region test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_regions
  # Regions
  # Returns the geographic definition and property mappings of regions matching the specified parameters.&lt;br&gt;&lt;br&gt; To request all regions in the world, omit the &#x60;ancestor&#x60; query parameter. To request all regions in a specific continent, country or other level, specify the ID of that region as the &#x60;ancestor&#x60;. Refer to the list of [top level regions](https://developers.expediagroup.com/docs/rapid/lodging/geography/geography-reference-lists). &lt;br&gt;&lt;br&gt; The response is a paginated list of regions. See the &#x60;Link&#x60; header in the 200 response section. 
  # @param accept Specifies the response format that the client would like to receive back. This must be &#x60;application/json&#x60;. 
  # @param accept_encoding Specifies the response encoding that the client would like to receive back. This must be &#x60;gzip&#x60;. 
  # @param user_agent The &#x60;User-Agent&#x60; header string from the customer&#39;s request, as captured by your integration. If you are building an application then the &#x60;User-Agent&#x60; value should be &#x60;{app name}/{app version}&#x60;. 
  # @param include Options for which content to return in the response. This parameter can be supplied multiple times with different values. The standard and details options cannot be requested together. The value must be lower case.   * standard - Include the metadata and basic hierarchy of each region.   * details - Include the metadata, coordinates and full hierarchy of each region.   * property_ids - Include the list of property IDs within the bounding polygon of each region.   * property_ids_expanded - Include the list of property IDs within the bounding polygon of each region and     property IDs from the surrounding area if minimal properties are within the region. 
  # @param language Desired language for the response as a subset of BCP47 format that only uses hyphenated pairs of two-digit language and country codes. Use only ISO 639-1 alpha-2 language codes and ISO 3166-1 alpha-2 country codes. &lt;br&gt;&lt;br&gt;Reference: * [W3 Language Tags](https://www.w3.org/International/articles/language-tags/) * [Language Options](https://developers.expediagroup.com/docs/rapid/resources/reference/language-options) 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_session_id Insert your own unique value for each user session, beginning with the first API call. Continue to pass the same value for each subsequent API call during the user&#39;s session, using a new value for every new customer session.&lt;br&gt; Including this value greatly eases EPS&#39;s internal debugging process for issues with partner requests, as it explicitly links together request paths for individual user&#39;s session. 
  # @option opts [String] :ancestor_id Search for regions whose ancestors include the requested ancestor region ID. Refer to the list of [top level regions](https://developers.expediagroup.com/docs/rapid/lodging/geography/geography-reference-lists). 
  # @option opts [String] :area Filter the results to regions that intersect with a specified area.&lt;br&gt;&lt;br&gt; The area may be defined in one of two ways:   * radius,region_id   * radius,latitude,longitude  Radius combined with region id would search an area that extends the number of kilometers out from the boundaries of the region in all directions.&lt;br&gt; Radius combined with a single point, specified by a latitude, longitude pair would search an area in a circle with the specified radius and the point as the center.&lt;br&gt; Radius should be specified in non-negative whole kilometers, decimals will return an error. A radius of 0 is allowed.&lt;br&gt; When specifying the area parameter, there will be a limit of 100 results, which can be narrowed further by the limit parameter.&lt;br&gt; Due to the number of results, unless &#x60;point_of_interest&#x60; is specified as the only type, regions of type &#x60;point_of_interest&#x60; will not be included in a request that filters to an area.&lt;br&gt;&lt;br&gt; An example use case would be searching for the closest 3 airports within 50 kilometers of a specified point.&lt;br&gt;   &#x60;&amp;type&#x3D;airport&amp;limit&#x3D;3&amp;area&#x3D;50,37.227924,-93.310036&#x60; 
  # @option opts [Array<String>] :country_code Filter the results to a specified ISO 3166-1 alpha-2 country code.  For more information see: [https://www.iso.org/obp/ui/#search/code/](https://www.iso.org/obp/ui/#search/code/) 
  # @option opts [Array<String>] :country_subdivision_code Filter the results down to only the ISO 3166-2 country subdivision.
  # @option opts [String] :iata_location_code Search for regions by the requested 3-character IATA location code, which will apply to both iata_airport_code and iata_airport_metro_code. The code must be upper case. 
  # @option opts [Float] :limit Limit the number of results returned. Using the area parameter will impose a max value of 100 for this whether specified or not. 
  # @option opts [String] :supply_source Options for which supply source you would like returned in the geography response. This parameter may only be supplied once and will return all properties that match the requested supply source. An error is thrown if the parameter is provided multiple times.   * &#x60;expedia&#x60; - Standard Expedia supply.   * &#x60;vrbo&#x60; - VRBO supply - This option is restricted to partners who have VRBO supply enabled for their profile. See [Vacation Rentals](https://developers.expediagroup.com/docs/rapid/lodging/vacation-rentals) for more information. 
  # @option opts [Array<String>] :type Filter the results to a specified region type. 
  # @option opts [String] :billing_terms This parameter is to specify the terms of how a resulting booking should be billed. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :partner_point_of_sale This parameter is to specify what point of sale is being used to shop and book. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :payment_terms This parameter is to specify what terms should be used when being paid for a resulting booking. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :platform_name This parameter is to specify what platform is being used to shop and book. If this field is needed, the value for this will be provided to you separately. 
  # @return [Array<Region>]
  describe 'get_regions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_geography
  # Properties within Polygon
  # Returns the properties within an custom polygon that represents a multi-city area or smaller. The coordinates of the polygon should be in [GeoJSON format](https://tools.ietf.org/html/rfc7946) and the polygon must conform to the following restrictions:   * Polygon size - diagonal distance of the polygon must be less than 500km   * Polygon type - only single polygons are supported   * Number of coordinates - must be &lt;&#x3D; 2000 
  # @param accept Specifies the response format that the client would like to receive back. This must be &#x60;application/json&#x60;. 
  # @param accept_encoding Specifies the response encoding that the client would like to receive back. This must be &#x60;gzip&#x60;. 
  # @param user_agent The &#x60;User-Agent&#x60; header string from the customer&#39;s request, as captured by your integration. If you are building an application then the &#x60;User-Agent&#x60; value should be &#x60;{app name}/{app version}&#x60;. 
  # @param include Options for which content to return in the response. The value must be lower case.   * property_ids - Include the property IDs. 
  # @param supply_source Options for which supply source you would like returned in the content response. This parameter may only be supplied once and will return all properties that match the requested supply source. An error is thrown if the parameter is provided multiple times.   * &#x60;expedia&#x60; - Standard Expedia supply.   * &#x60;vrbo&#x60; - VRBO supply - This option is restricted to partners who have VRBO supply enabled for their profile. See [Vacation Rentals](https://developers.expediagroup.com/docs/rapid/lodging/vacation-rentals) for more information. 
  # @param properties_geo_json_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_session_id Insert your own unique value for each user session, beginning with the first API call. Continue to pass the same value for each subsequent API call during the user&#39;s session, using a new value for every new customer session.&lt;br&gt; Including this value greatly eases EPS&#39;s internal debugging process for issues with partner requests, as it explicitly links together request paths for individual user&#39;s session. 
  # @option opts [String] :billing_terms This parameter is to specify the terms of how a resulting booking should be billed. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :partner_point_of_sale This parameter is to specify what point of sale is being used to shop and book. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :payment_terms This parameter is to specify what terms should be used when being paid for a resulting booking. If this field is needed, the value for this will be provided to you separately. 
  # @option opts [String] :platform_name This parameter is to specify what platform is being used to shop and book. If this field is needed, the value for this will be provided to you separately. 
  # @return [Hash<String, PropertyGeography>]
  describe 'post_geography test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
