=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetPropertyContent200ResponseValueAllInclusive
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetPropertyContent200ResponseValueAllInclusive do
  let(:instance) { ExpediaRapid::GetPropertyContent200ResponseValueAllInclusive.new }

  describe 'test an instance of GetPropertyContent200ResponseValueAllInclusive' do
    it 'should create an instance of GetPropertyContent200ResponseValueAllInclusive' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetPropertyContent200ResponseValueAllInclusive)
    end
  end

  describe 'test attribute "all_rate_plans"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "some_rate_plans"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
