=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetReservation200ResponseInnerRoomsInnerRateCancelRefund
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetReservation200ResponseInnerRoomsInnerRateCancelRefund do
  let(:instance) { ExpediaRapid::GetReservation200ResponseInnerRoomsInnerRateCancelRefund.new }

  describe 'test an instance of GetReservation200ResponseInnerRoomsInnerRateCancelRefund' do
    it 'should create an instance of GetReservation200ResponseInnerRoomsInnerRateCancelRefund' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetReservation200ResponseInnerRoomsInnerRateCancelRefund)
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "currency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
