=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetAvailability200ResponseInnerRoomsInnerRatesInnerBedGroupsValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetAvailability200ResponseInnerRoomsInnerRatesInnerBedGroupsValue do
  let(:instance) { ExpediaRapid::GetAvailability200ResponseInnerRoomsInnerRatesInnerBedGroupsValue.new }

  describe 'test an instance of GetAvailability200ResponseInnerRoomsInnerRatesInnerBedGroupsValue' do
    it 'should create an instance of GetAvailability200ResponseInnerRoomsInnerRatesInnerBedGroupsValue' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetAvailability200ResponseInnerRoomsInnerRatesInnerBedGroupsValue)
    end
  end

  describe 'test attribute "links"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "configuration"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
