=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetCalendarAvailability200ResponseInnerDaysInnerStayConstraints
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetCalendarAvailability200ResponseInnerDaysInnerStayConstraints do
  let(:instance) { ExpediaRapid::GetCalendarAvailability200ResponseInnerDaysInnerStayConstraints.new }

  describe 'test an instance of GetCalendarAvailability200ResponseInnerDaysInnerStayConstraints' do
    it 'should create an instance of GetCalendarAvailability200ResponseInnerDaysInnerStayConstraints' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetCalendarAvailability200ResponseInnerDaysInnerStayConstraints)
    end
  end

  describe 'test attribute "min_stay"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "max_stay"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
