=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetPropertyContent200ResponseValueRoomsValueBedGroupsValueConfigurationInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetPropertyContent200ResponseValueRoomsValueBedGroupsValueConfigurationInner do
  let(:instance) { ExpediaRapid::GetPropertyContent200ResponseValueRoomsValueBedGroupsValueConfigurationInner.new }

  describe 'test an instance of GetPropertyContent200ResponseValueRoomsValueBedGroupsValueConfigurationInner' do
    it 'should create an instance of GetPropertyContent200ResponseValueRoomsValueBedGroupsValueConfigurationInner' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetPropertyContent200ResponseValueRoomsValueBedGroupsValueConfigurationInner)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "quantity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
