=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetStatisticsReference200ResponseValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetStatisticsReference200ResponseValue do
  let(:instance) { ExpediaRapid::GetStatisticsReference200ResponseValue.new }

  describe 'test an instance of GetStatisticsReference200ResponseValue' do
    it 'should create an instance of GetStatisticsReference200ResponseValue' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ExpediaRapid::GetStatisticsReference200ResponseValue)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "has_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
