=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValue do
  let(:instance) { ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValue.new }

  describe 'test an instance of GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValue' do
    it 'should create an instance of GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValue' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValue)
    end
  end

  describe 'test attribute "nightly"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "stay"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "totals"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "fees"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
