=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerPromotionsValueAddsValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerPromotionsValueAddsValue do
  let(:instance) { ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerPromotionsValueAddsValue.new }

  describe 'test an instance of GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerPromotionsValueAddsValue' do
    it 'should create an instance of GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerPromotionsValueAddsValue' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerPromotionsValueAddsValue)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["food_and_beverage", "entertainment", "service", "activity", "credit"])
      # validator.allowable_values.each do |value|
      #   expect { instance.category = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "offer_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["buy_one_get_one_free", "credit", "discount", "free", "voucher"])
      # validator.allowable_values.each do |value|
      #   expect { instance.offer_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "frequency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["unknown", "per_night", "per_day", "per_stay", "per_week", "round_trip", "one_way"])
      # validator.allowable_values.each do |value|
      #   expect { instance.frequency = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "person_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
