=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PostPaymentSessionsRequestCustomerAccountDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PostPaymentSessionsRequestCustomerAccountDetails do
  let(:instance) { ExpediaRapid::PostPaymentSessionsRequestCustomerAccountDetails.new }

  describe 'test an instance of PostPaymentSessionsRequestCustomerAccountDetails' do
    it 'should create an instance of PostPaymentSessionsRequestCustomerAccountDetails' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::PostPaymentSessionsRequestCustomerAccountDetails)
    end
  end

  describe 'test attribute "authentication_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["guest", "own_credentials", "federated_id", "issuer_credentials", "third_party_authentication", "fido_authentication"])
      # validator.allowable_values.each do |value|
      #   expect { instance.authentication_method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "authentication_timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "create_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "change_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "password_change_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "add_card_attempts"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "account_purchases"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
