=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PostPaymentSessionsRequestPaymentsInnerAdditionalHandling
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PostPaymentSessionsRequestPaymentsInnerAdditionalHandling do
  let(:instance) { ExpediaRapid::PostPaymentSessionsRequestPaymentsInnerAdditionalHandling.new }

  describe 'test an instance of PostPaymentSessionsRequestPaymentsInnerAdditionalHandling' do
    it 'should create an instance of PostPaymentSessionsRequestPaymentsInnerAdditionalHandling' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ExpediaRapid::PostPaymentSessionsRequestPaymentsInnerAdditionalHandling)
    end
  end

  describe 'test attribute "authorized_expenses"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["prestay_expenses_only", "total_booking_amount", "total_plus_incidentals", "see_authorization_form"])
      # validator.allowable_values.each do |value|
      #   expect { instance.authorized_expenses = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "specified_incidental_expenses"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["breakfast", "entertainment", "internet", "meeting_expenses", "other_food_beverage", "parking", "phone", "taxes", "transfer", "other"])
      # validator.allowable_values.each do |value|
      #   expect { instance.specified_incidental_expenses = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "total_charges_allowed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_cvc_required"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "authorizing_company"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "card_contact"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "max_payment_attempt_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "payment_allowable_period_start"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "payment_allowable_period_end"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
