=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PriceCheck200ResponseTraderInformation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PriceCheck200ResponseTraderInformation do
  let(:instance) { ExpediaRapid::PriceCheck200ResponseTraderInformation.new }

  describe 'test an instance of PriceCheck200ResponseTraderInformation' do
    it 'should create an instance of PriceCheck200ResponseTraderInformation' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::PriceCheck200ResponseTraderInformation)
    end
  end

  describe 'test attribute "traders"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "terms_and_conditions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
