=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PromotionsItinerary
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PromotionsItinerary do
  let(:instance) { ExpediaRapid::PromotionsItinerary.new }

  describe 'test an instance of PromotionsItinerary' do
    it 'should create an instance of PromotionsItinerary' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::PromotionsItinerary)
    end
  end

  describe 'test attribute "value_adds"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
