=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PropertyManagerLinks
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PropertyManagerLinks do
  let(:instance) { ExpediaRapid::PropertyManagerLinks.new }

  describe 'test an instance of PropertyManagerLinks' do
    it 'should create an instance of PropertyManagerLinks' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::PropertyManagerLinks)
    end
  end

  describe 'test attribute "image"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
