=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PutCompletePaymentSession200ResponseLinks
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PutCompletePaymentSession200ResponseLinks do
  let(:instance) { ExpediaRapid::PutCompletePaymentSession200ResponseLinks.new }

  describe 'test an instance of PutCompletePaymentSession200ResponseLinks' do
    it 'should create an instance of PutCompletePaymentSession200ResponseLinks' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::PutCompletePaymentSession200ResponseLinks)
    end
  end

  describe 'test attribute "retrieve"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "resume"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cancel"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
