=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::PutCompletePaymentSession200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::PutCompletePaymentSession200Response do
  let(:instance) { ExpediaRapid::PutCompletePaymentSession200Response.new }

  describe 'test an instance of PutCompletePaymentSession200Response' do
    it 'should create an instance of PutCompletePaymentSession200Response' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::PutCompletePaymentSession200Response)
    end
  end

  describe 'test attribute "itinerary_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "links"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "trader_information"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
