=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::SupplierTransparency
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::SupplierTransparency do
  let(:instance) { ExpediaRapid::SupplierTransparency.new }

  describe 'test an instance of SupplierTransparency' do
    it 'should create an instance of SupplierTransparency' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::SupplierTransparency)
    end
  end

  describe 'test attribute "point_of_sale_display_to_share"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "company_name_to_share"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "consent_to_share"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
