=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::TravelCompanion
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::TravelCompanion do
  let(:instance) { ExpediaRapid::TravelCompanion.new }

  describe 'test an instance of TravelCompanion' do
    it 'should create an instance of TravelCompanion' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::TravelCompanion)
    end
  end

end
