=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ExpediaRapid::UnavailableReason
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ExpediaRapid::UnavailableReason do
  let(:instance) { ExpediaRapid::UnavailableReason.new }

  describe 'test an instance of UnavailableReason' do
    it 'should create an instance of UnavailableReason' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(ExpediaRapid::UnavailableReason)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["adults_exceed_threshold", "children_exceed_threshold", "infants_exceed_threshold", "minimum_child_age", "maximum_occupancy", "checkin_not_allowed", "checkout_not_allowed", "minimum_stay", "maximum_stay", "restricted_dates", "same_day_restrictions", "maximum_rooms", "children_not_supported", "minimum_advance_purchase", "maximum_advance_purchase", "partial_inventory_available", "no_inventory_available"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
