=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  class CategoryValueAdd
    FOOD_AND_BEVERAGE = "food_and_beverage".freeze
    ENTERTAINMENT = "entertainment".freeze
    SERVICE = "service".freeze
    ACTIVITY = "activity".freeze
    CREDIT = "credit".freeze

    def self.all_vars
      @all_vars ||= [FOOD_AND_BEVERAGE, ENTERTAINMENT, SERVICE, ACTIVITY, CREDIT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CategoryValueAdd.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CategoryValueAdd"
    end
  end
end
