=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  class Frequency
    UNKNOWN = "unknown".freeze
    PER_NIGHT = "per_night".freeze
    PER_DAY = "per_day".freeze
    PER_STAY = "per_stay".freeze
    PER_WEEK = "per_week".freeze
    ROUND_TRIP = "round_trip".freeze
    ONE_WAY = "one_way".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, PER_NIGHT, PER_DAY, PER_STAY, PER_WEEK, ROUND_TRIP, ONE_WAY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Frequency.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Frequency"
    end
  end
end
