=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  # Descriptions of a property.
  class GetPropertyContent200ResponseValueDescriptions
    # Describes general building amenities at the property.
    attr_accessor :amenities

    # Describes dining accommodations at the property.
    attr_accessor :dining

    # Describes any recent room or property renovations.
    attr_accessor :renovations

    # States the source of the property's star rating (such as a regional or national tourism agency) and any other ratings claimed.
    attr_accessor :national_ratings

    # Describes any business-specific amenities at the property, e.g. conference rooms.
    attr_accessor :business_amenities

    # Describes typical room amenities.
    attr_accessor :rooms

    # Nearby attractions/areas, often including distances from the property.
    attr_accessor :attractions

    # General location as entered by the property.
    attr_accessor :location

    # A headline description for the property.
    attr_accessor :headline

    # A general description of a vacation rental property.
    attr_accessor :general

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amenities' => :'amenities',
        :'dining' => :'dining',
        :'renovations' => :'renovations',
        :'national_ratings' => :'national_ratings',
        :'business_amenities' => :'business_amenities',
        :'rooms' => :'rooms',
        :'attractions' => :'attractions',
        :'location' => :'location',
        :'headline' => :'headline',
        :'general' => :'general'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amenities' => :'String',
        :'dining' => :'String',
        :'renovations' => :'String',
        :'national_ratings' => :'String',
        :'business_amenities' => :'String',
        :'rooms' => :'String',
        :'attractions' => :'String',
        :'location' => :'String',
        :'headline' => :'String',
        :'general' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ExpediaRapid::GetPropertyContent200ResponseValueDescriptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ExpediaRapid::GetPropertyContent200ResponseValueDescriptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amenities')
        self.amenities = attributes[:'amenities']
      end

      if attributes.key?(:'dining')
        self.dining = attributes[:'dining']
      end

      if attributes.key?(:'renovations')
        self.renovations = attributes[:'renovations']
      end

      if attributes.key?(:'national_ratings')
        self.national_ratings = attributes[:'national_ratings']
      end

      if attributes.key?(:'business_amenities')
        self.business_amenities = attributes[:'business_amenities']
      end

      if attributes.key?(:'rooms')
        self.rooms = attributes[:'rooms']
      end

      if attributes.key?(:'attractions')
        self.attractions = attributes[:'attractions']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'headline')
        self.headline = attributes[:'headline']
      end

      if attributes.key?(:'general')
        self.general = attributes[:'general']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amenities == o.amenities &&
          dining == o.dining &&
          renovations == o.renovations &&
          national_ratings == o.national_ratings &&
          business_amenities == o.business_amenities &&
          rooms == o.rooms &&
          attractions == o.attractions &&
          location == o.location &&
          headline == o.headline &&
          general == o.general
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amenities, dining, renovations, national_ratings, business_amenities, rooms, attractions, location, headline, general].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ExpediaRapid.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
