=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  class NightChargeType
    BASE_RATE = "base_rate".freeze
    TAX_AND_SERVICE_FEE = "tax_and_service_fee".freeze
    EXTRA_PERSON_FEE = "extra_person_fee".freeze
    PROPERTY_FEE = "property_fee".freeze
    SALES_TAX = "sales_tax".freeze
    ADJUSTMENT = "adjustment".freeze
    RECOVERY_CHARGES_AND_FEES = "recovery_charges_and_fees".freeze
    TRAVELER_SERVICE_FEE = "traveler_service_fee".freeze

    def self.all_vars
      @all_vars ||= [BASE_RATE, TAX_AND_SERVICE_FEE, EXTRA_PERSON_FEE, PROPERTY_FEE, SALES_TAX, ADJUSTMENT, RECOVERY_CHARGES_AND_FEES, TRAVELER_SERVICE_FEE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if NightChargeType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #NightChargeType"
    end
  end
end
