=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  # Parent object for additional VCC handling instructions, to be included as part of the payment object when virtual_card is the requested payment type for property collect inventory. If not included, existing behavior regarding handling of VCCs with property collect inventory is to be preserved. This object will be ignored for non-property collect/non-VCC transactions. total_charges_allowed represents the total ceiling of all charges allowed on the VCC, including the booking price and any allowed incidentals. The value of total_charges_allowed must be at least the booking value.
  class PostPaymentSessionsRequestPaymentsInnerAdditionalHandling
    # Indicates which types of expenses are authorized to be charged to the VCC. * `prestay_expenses_only` - Indicates that the provided VCC is for pre-stay charges only (e.g.,   deposits, cancellation fees, no-show fees). A physical card must be presented at check-in for any   remaining balance, as well as incidentals. * `total_booking_amount` - Indicates that both pre-stay charges and the total booking amount are   authorized, but no incidentals are authorized. A physical card must be presented at check-in for any   incidentals. * `total_plus_incidentals` - Indicates that pre-stay, total booking, and incidental expenses are   authorized. See `specified_incidental_expenses`. A physical card may be required for additional   incidental expenses. * `see_authorization_form` - Indicates that a property should refer to the authorization form that will   be sent either by the card provider or the authorizing company.
    attr_accessor :authorized_expenses

    # Included list of enumerated categories to restrict the authorized incidentals. This is only utilized when `authorized_expenses` is supplied with `total_plus_incidentals` and restrictions on incidentals are desired.<br> Example: To allow any incidental expenses, specify `authorized_expenses` equal to `total_plus_incidentals` and omit `specified_incidental_expenses`.
    attr_accessor :specified_incidental_expenses

    attr_accessor :total_charges_allowed

    # Indicates whether a CVC is required for the provided VCC. If this is marked required, the security_code field for the payment MUST be provided.
    attr_accessor :is_cvc_required

    # Company that will issue the authorization form for the virtual credit card payment.
    attr_accessor :authorizing_company

    attr_accessor :card_contact

    # Requested limit to number of payment attempts.
    attr_accessor :max_payment_attempt_count

    # Start date for valid range of the VCC payment instrument, in ISO 8601 format (YYYY-MM-DD).
    attr_accessor :payment_allowable_period_start

    # End date for valid range of the VCC payment instrument, in ISO 8601 format (YYYY-MM-DD).
    attr_accessor :payment_allowable_period_end

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'authorized_expenses' => :'authorized_expenses',
        :'specified_incidental_expenses' => :'specified_incidental_expenses',
        :'total_charges_allowed' => :'total_charges_allowed',
        :'is_cvc_required' => :'is_cvc_required',
        :'authorizing_company' => :'authorizing_company',
        :'card_contact' => :'card_contact',
        :'max_payment_attempt_count' => :'max_payment_attempt_count',
        :'payment_allowable_period_start' => :'payment_allowable_period_start',
        :'payment_allowable_period_end' => :'payment_allowable_period_end'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'authorized_expenses' => :'String',
        :'specified_incidental_expenses' => :'Array<String>',
        :'total_charges_allowed' => :'GetAdditionalAvailability200ResponseInnerRoomsInnerRatesInnerOccupancyPricingValueTotalsInclusiveBillableCurrency',
        :'is_cvc_required' => :'Boolean',
        :'authorizing_company' => :'String',
        :'card_contact' => :'PostPaymentSessionsRequestPaymentsInnerAdditionalHandlingCardContact',
        :'max_payment_attempt_count' => :'Float',
        :'payment_allowable_period_start' => :'String',
        :'payment_allowable_period_end' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ExpediaRapid::PostPaymentSessionsRequestPaymentsInnerAdditionalHandling` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ExpediaRapid::PostPaymentSessionsRequestPaymentsInnerAdditionalHandling`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'authorized_expenses')
        self.authorized_expenses = attributes[:'authorized_expenses']
      else
        self.authorized_expenses = nil
      end

      if attributes.key?(:'specified_incidental_expenses')
        if (value = attributes[:'specified_incidental_expenses']).is_a?(Array)
          self.specified_incidental_expenses = value
        end
      end

      if attributes.key?(:'total_charges_allowed')
        self.total_charges_allowed = attributes[:'total_charges_allowed']
      end

      if attributes.key?(:'is_cvc_required')
        self.is_cvc_required = attributes[:'is_cvc_required']
      end

      if attributes.key?(:'authorizing_company')
        self.authorizing_company = attributes[:'authorizing_company']
      end

      if attributes.key?(:'card_contact')
        self.card_contact = attributes[:'card_contact']
      end

      if attributes.key?(:'max_payment_attempt_count')
        self.max_payment_attempt_count = attributes[:'max_payment_attempt_count']
      end

      if attributes.key?(:'payment_allowable_period_start')
        self.payment_allowable_period_start = attributes[:'payment_allowable_period_start']
      end

      if attributes.key?(:'payment_allowable_period_end')
        self.payment_allowable_period_end = attributes[:'payment_allowable_period_end']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @authorized_expenses.nil?
        invalid_properties.push('invalid value for "authorized_expenses", authorized_expenses cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @authorized_expenses.nil?
      authorized_expenses_validator = EnumAttributeValidator.new('String', ["prestay_expenses_only", "total_booking_amount", "total_plus_incidentals", "see_authorization_form"])
      return false unless authorized_expenses_validator.valid?(@authorized_expenses)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] authorized_expenses Object to be assigned
    def authorized_expenses=(authorized_expenses)
      validator = EnumAttributeValidator.new('String', ["prestay_expenses_only", "total_booking_amount", "total_plus_incidentals", "see_authorization_form"])
      unless validator.valid?(authorized_expenses)
        fail ArgumentError, "invalid value for \"authorized_expenses\", must be one of #{validator.allowable_values}."
      end
      @authorized_expenses = authorized_expenses
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          authorized_expenses == o.authorized_expenses &&
          specified_incidental_expenses == o.specified_incidental_expenses &&
          total_charges_allowed == o.total_charges_allowed &&
          is_cvc_required == o.is_cvc_required &&
          authorizing_company == o.authorizing_company &&
          card_contact == o.card_contact &&
          max_payment_attempt_count == o.max_payment_attempt_count &&
          payment_allowable_period_start == o.payment_allowable_period_start &&
          payment_allowable_period_end == o.payment_allowable_period_end
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [authorized_expenses, specified_incidental_expenses, total_charges_allowed, is_cvc_required, authorizing_company, card_contact, max_payment_attempt_count, payment_allowable_period_start, payment_allowable_period_end].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ExpediaRapid.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
