=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  class PostItineraryRequest
    # Your unique reference value. This field supports from 3 to a maximum of 28 characters and is required to be unique (if provided). Entering special characters (\"<\", \">\", \"(\", \")\", and \"&\") in this field will result in the request being rejected. 
    attr_accessor :affiliate_reference_id

    # Flag for placing a booking on hold. The booking will be released if the resume link is not followed within the hold period. Please refer to our Hold and Resume documentation. 
    attr_accessor :hold

    # Email address for the customer. Must adhere to standard RFC 822 email format. Special characters (\"<\", \">\", \"(\", \")\", and \"&\") entered in this field will be re-encoded. 
    attr_accessor :email

    attr_accessor :phone

    attr_accessor :rooms

    # Required if payment information prior to booking was not submitted. If register payments was called prior to this call, do not submit payment information again. 
    attr_accessor :payments

    # Field that stores up to 256 characters of additional metadata with the itinerary. Will be returned on all retrieve responses for this itinerary. The data must be in the format 'key1:value|key2:value|key3:value'. Other Special characters (\"<\", \">\", \"(\", \")\", and \"&\") entered in this field will be re-encoded. 
    attr_accessor :affiliate_metadata

    # The customer's taxpayer identification number that is provided by the government to nationals or resident aliens. This number should be collected from individuals that pay taxes or participate in activities that provide revenue for one or more tax types. *Note:* This value is only needed from Brazilian and Indian customers. 
    attr_accessor :tax_registration_number

    # Custom traveler handling instructions for the hotel. Do not include PCI sensitive data, such as credit card numbers, in this field.
    attr_accessor :traveler_handling_instructions

    attr_accessor :invoicing

    attr_accessor :supplier_transparency

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'affiliate_reference_id' => :'affiliate_reference_id',
        :'hold' => :'hold',
        :'email' => :'email',
        :'phone' => :'phone',
        :'rooms' => :'rooms',
        :'payments' => :'payments',
        :'affiliate_metadata' => :'affiliate_metadata',
        :'tax_registration_number' => :'tax_registration_number',
        :'traveler_handling_instructions' => :'traveler_handling_instructions',
        :'invoicing' => :'invoicing',
        :'supplier_transparency' => :'supplier_transparency'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'affiliate_reference_id' => :'String',
        :'hold' => :'Boolean',
        :'email' => :'String',
        :'phone' => :'PostItineraryRequestPhone',
        :'rooms' => :'Array<PostItineraryRequestRoomsInner>',
        :'payments' => :'Array<PostPaymentSessionsRequestPaymentsInner>',
        :'affiliate_metadata' => :'String',
        :'tax_registration_number' => :'String',
        :'traveler_handling_instructions' => :'String',
        :'invoicing' => :'GetReservation200ResponseInnerInvoicing',
        :'supplier_transparency' => :'GetReservation200ResponseInnerSupplierTransparency'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ExpediaRapid::PostItineraryRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ExpediaRapid::PostItineraryRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'affiliate_reference_id')
        self.affiliate_reference_id = attributes[:'affiliate_reference_id']
      end

      if attributes.key?(:'hold')
        self.hold = attributes[:'hold']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      else
        self.phone = nil
      end

      if attributes.key?(:'rooms')
        if (value = attributes[:'rooms']).is_a?(Array)
          self.rooms = value
        end
      else
        self.rooms = nil
      end

      if attributes.key?(:'payments')
        if (value = attributes[:'payments']).is_a?(Array)
          self.payments = value
        end
      end

      if attributes.key?(:'affiliate_metadata')
        self.affiliate_metadata = attributes[:'affiliate_metadata']
      end

      if attributes.key?(:'tax_registration_number')
        self.tax_registration_number = attributes[:'tax_registration_number']
      end

      if attributes.key?(:'traveler_handling_instructions')
        self.traveler_handling_instructions = attributes[:'traveler_handling_instructions']
      end

      if attributes.key?(:'invoicing')
        self.invoicing = attributes[:'invoicing']
      end

      if attributes.key?(:'supplier_transparency')
        self.supplier_transparency = attributes[:'supplier_transparency']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @phone.nil?
        invalid_properties.push('invalid value for "phone", phone cannot be nil.')
      end

      if @rooms.nil?
        invalid_properties.push('invalid value for "rooms", rooms cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @email.nil?
      return false if @phone.nil?
      return false if @rooms.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          affiliate_reference_id == o.affiliate_reference_id &&
          hold == o.hold &&
          email == o.email &&
          phone == o.phone &&
          rooms == o.rooms &&
          payments == o.payments &&
          affiliate_metadata == o.affiliate_metadata &&
          tax_registration_number == o.tax_registration_number &&
          traveler_handling_instructions == o.traveler_handling_instructions &&
          invoicing == o.invoicing &&
          supplier_transparency == o.supplier_transparency
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [affiliate_reference_id, hold, email, phone, rooms, payments, affiliate_metadata, tax_registration_number, traveler_handling_instructions, invoicing, supplier_transparency].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ExpediaRapid.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
