=begin
#Rapid

#EPS Rapid V3

The version of the OpenAPI document: v3

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ExpediaRapid
  class TravelCompanion
    FAMILY = "family".freeze
    FAMILY_WITH_CHILDREN = "family_with_children".freeze
    PARTNER = "partner".freeze
    SELF = "self".freeze
    FRIENDS = "friends".freeze
    PET = "pet".freeze

    def self.all_vars
      @all_vars ||= [FAMILY, FAMILY_WITH_CHILDREN, PARTNER, SELF, FRIENDS, PET].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TravelCompanion.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TravelCompanion"
    end
  end
end
